### ISSUE TITLE
Undocumented: How to allow based on subscription

### ISSUE THREAD

**Issue by j6k4m8** [Goluis/cottz-flow-router-auth#6]
Consider the following code:

```
FlowRouter.Auth.allow(() => {
    return !!ProhibitedThings.findOne();
}, ProhibitedRoutes);
```

We only `publish` the `ProhibitedThings` collection if you are an authorized user — and this is handled on the server. So on the frontend, the router knows if you're an authorized user by checking for the existence of `ProhibitedThings`. 

But there's a race-condition afoot: If you directly hit a route in `ProhibitedRoutes`, it's possible that the subscription has not completely run yet (and in practice, I find this to always be the case), and so you are redirected _always_ to the `FlowRouter.Auth.redirect` page.

What is the "correct" way of fixing this? I've tried 

```
ProhibitedRoutes.route('/',
    subscriptions: function(params) {
        this.register('prohibited_things', Meteor.subscribe('prohibited_things'));
    }
    [. . .]
}
```

with no success.

**Comment by Goluis** [comment]
Mmmm it must be for this:
```js
// client.js
if (Meteor.user() || FlowRouter.subsReady()) {
```
with this should work:
```js
if (Meteor.user() && FlowRouter.subsReady()) {
```

**Comment by j6k4m8** [comment]
I'm not quite sure where you mean I should be including this — is this inside the Auth.allow?

**Comment by Goluis** [comment]
No, it is a code within the package, when I did thought to use it only for validations with the user, the bove change should wait for all subscriptions rather than only for the user.

I will make some changes and publish it ^^

**Comment by j6k4m8** [comment]
Aha! Fantastic. Thank you very much! Keep me updated :)

**Comment by Goluis** [comment]
I publish it, can you check it again?

**Comment by j6k4m8** [comment]
Looks perfect — thank you so much for the quick turnaround time!
