### ISSUE TITLE
Redirect needs to be done in sync

### ISSUE THREAD

**Issue by j6k4m8** [Goluis/cottz-flow-router-auth#7]
By adding the (reduced-case) following code:

```
FlowRouter.Auth.allow(function() {
    return false;
});
```

...it results in the following error in the client:

```
Error: redirect needs to be done in sync
    at doRedirect (http://localhost:3010/packages/kadira_flow-router.js?hash=09ea12875d3801955ee70797bf8e4a70feebc570:147:13)
    at http://localhost:3010/packages/cottz_flow-router-auth.js?hash=6cfbc85eecb23dcb8087da90ef79e95c877e8782:145:44
    at http://localhost:3010/packages/minimongo.js?hash=88217d643bc16fdf3505c6d4b2b8f5ddc400c49a:211:14
```

...but all of my routes are still accessible to a logged-out user.

**Comment by lfades** [comment]
I don't know what happened to my package, but it no longer works in my application with Meteor 1.2.1 unless I copy it directly within packages. It works correctly in meteor 1.3.
